# Change these first
owner: sdcagroup # Your GitHub organization or username, where this repository lives
repo: SiteCheck # The name of this repository
user-agent: sdcagroup

sites:
  - name: Holly North
    url: https://hollynorth.com
  - name: Hoop Tape
    url: https://hooptapecanada.com
  - name: Sicom
    url: https://sicomindustries.com
  - name: The Tickle Trunk
    url: https://thetickletrunk.com
  - name: Stu Bell
    url: https://stubell.com.com
  #- name: IPv6 test
  #  url: forwardemail.net
  #  port: 80
  #  check: "tcp-ping"
  #  ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /SiteCheck
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Website monitor and status page, powered entirely by GitHub."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
